--drop if not exists
--DROP TABLE IF EXISTS USERS, FILMS, ACTORS, FILMACTORS;

CREATE TABLE USERS (
  id SERIAL PRIMARY KEY, 
  email VARCHAR (150) UNIQUE NOT NULL,
  password VARCHAR (200) NOT NULL,
  is_admin boolean);